//
// Created by Acer on 11.01.2022.
//

#include <iostream>
#include <algorithm>
#include "Galton.h"

using namespace std;

void Galton::InitialiseTableau(mt19937 gen)
{
	static std::uniform_int_distribution<> distrib(0, 1);

	int indice;

	for(int i=0; i < nbrDeBilles; ++i) {

		indice = 0;
		for (int n = 0; n < hauteur; ++n) {
			//Use `distrib` to transform the random unsigned int generated by gen into an int in [1, 6]
			indice += distrib(gen);
		}
		tableau[indice] += 1;
	}
}

void Galton::AfficherTableauEtoiles()
{
	for (int i = (*max_element(tableau.begin(), tableau.end())); i > 0; --i)
	{
		// cout << i; // DEBUG

		for (int& val : tableau)
		{
			cout << (val>= i ? "*" : " ");
		}
		cout << endl;
	}
}

